secret=somerandomsecret1234SOMERANDOMSECRETLifeCanBeMeaningful1234SOMERANDOMSECRETLifeCanBeGo
spring.datasource.url = jdbc:mysql://localhost:3306/mydb?createDatabaseIfNotExist=true
spring.datasource.username = newuser1
spring.datasource.password = newuser1
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
